Emc/9 activity type mapping
KlimaDAO/bezos-frontend pull request #48
Opened 2023-01-20 05:56 UTC by 0xemc

## Description

* Activity labels and text determined by ActivityType
* Activity extracted as component
* Seller specific utils refactored to generic addresses
* User addresses as hyperlinks

## Related Ticket

Resolves KlimaDAO/bezos-frontend#9 

## Changes

| Before  | After  |
|---------|--------|
|![image](https://user-images.githubusercontent.com/7104689/213627523-12425bd9-be3e-47f7-a7ff-cb4f0b352632.png)|![image](https://user-images.githubusercontent.com/7104689/213628391-072ad450-795a-495d-8813-826b6b8468d4.png)|

## Remaining

* User addresses as ens (kns) names

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

2023-01-20 09:27 UTC, ladytrekker reviewed
Thanks, looks good 🌟 

Some comment belows with suggestions and questions.

I will also ping @Atmosfearful  for a quick review.

Concerning your comment

> User addresses as ens (kns) names

=> let's discuss this in a follow up 
I created a ticket: https://github.com/Atmosfearful/bezos-frontend/issues/49

2023-01-20 09:59 UTC, ladytrekker commented
I rebased with staging again
That means you need to rebase your PR with bezos-main again too.
This will be now the usual flow until go-live 🚀 

And by the way: Thanks for the commit history you did in this PR! 🙇 

FYI:
Atmos wrote a small wiki page too concerning rebasing
https://github.com/Atmosfearful/bezos-frontend/wiki

2023-01-21 01:19 UTC, Atmosfearful requested changes

2023-01-23 09:49 UTC, ladytrekker approved these changes
Thanks

2023-01-23 09:50 UTC, merged